#
# Copyright 2018 Asylo authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file lists the set of system calls for which to generate bridge
# and serialization code across the enclave boundary in Asylo.
#
# The format for this file can be found at:
# third_party/asylo/platform/arch/sgx/host_calls_generator/host_calls.proto

######################################
##                IO                ##
######################################

host_calls {
  name: "pread"
  return_type: "ssize_t"
  parameters {
    name: "fd"
    type: "int"
  }
  parameters {
    name: "buf"
    type: "void *"
    pointer_attributes {
      attribute: OUT
    }
    pointer_attributes {
      attribute: SIZE
      attribute_expression: "count"
    }
  }
  parameters {
    name: "count"
    type: "size_t"
  }
  parameters {
    name: "offset"
    type: "off_t"
  }
}

####################################
##             Futex              ##
####################################

host_calls {
  name: "sys_futex_wait"
  parameters {
    name: "futex"
    type: "int32_t *"
    pointer_attributes {
      attribute: USER_CHECK
    }
  }
  parameters {
    name: "expected"
    type: "int32_t"
  }
  return_type: "void"
}

host_calls {
  name: "sys_futex_wake"
  parameters {
    name: "futex"
    type: "int32_t *"
    pointer_attributes {
      attribute: USER_CHECK
    }
  }
  return_type: "void"
}
