#
# Copyright 2018 Asylo authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

licenses(["notice"])  # Apache v2.0

# Build targets for the whole-application wrapper and its tests.

load(
    "//asylo/bazel:asylo.bzl",
    "cc_test",
)

# A utility for converting various representations of argv.
cc_library(
    name = "argv",
    srcs = ["argv.cc"],
    hdrs = ["argv.h"],
    deps = [
        "@com_google_absl//absl/strings",
        "@com_google_protobuf//:protobuf_lite",
    ],
)

# A test of Argv.
cc_test(
    name = "argv_test",
    srcs = ["argv_test.cc"],
    enclave_test_name = "argv_enclave_test",
    deps = [
        ":argv",
        "//asylo/test/util:test_main",
        "@com_google_absl//absl/base:core_headers",
        "@com_google_googletest//:gtest",
        "@com_google_protobuf//:protobuf_lite",
    ],
)
